// <auto-generated />
using GrandChessTree.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrandChessTree.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250131191413_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrandChessTree.Api.Database.D10SearchTask", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<decimal>("AvailableAt")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("available_at");

                    b.Property<long>("PassCount")
                        .HasColumnType("bigint")
                        .HasColumnName("pass_count");

                    b.HasKey("Id");

                    b.ToTable("d10_search_task");
                });
#pragma warning restore 612, 618
        }
    }
}
