#!/usr/bin/env bash
# Clone, build, and verify perft_cpu_2026 → bin/perft_cpu_2026/build/perft_cpu.
#
# perft_cpu_2026 (Ankan Banerjee) is a perft-only CLI tool, not a UCI engine.
# PerftWar drives it via wrappers/perft_cpu_2026/run.sh.
#
# Two upstream compiler-compatibility issues fixed here without source edits:
#
#   1. MSVC's `__assume(x)` is used unconditionally in MoveGeneratorBitboard.h.
#      We force-include a tiny compat header that maps it to `__builtin_assume`
#      on clang and `do { if (!(x)) __builtin_unreachable(); } while(0)` on gcc.
#
#   2. Two-phase template lookup in gcc 13 rejects some unqualified calls
#      (`countMoves was not declared in this scope` errors). `-fpermissive`
#      downgrades those rejections to warnings.

ENGINE="perft_cpu_2026"
REPO="https://github.com/ankan-ban/perft_cpu_2026"
ENGINE_DIR="bin/perft_cpu_2026"
BINARY="$ENGINE_DIR/build/perft_cpu"
WRAPPER="wrappers/perft_cpu_2026/run.sh"

# shellcheck source=_common.sh
source "$(cd "$(dirname "$0")" && pwd)/_common.sh"

# --- Toolchain preflight ---------------------------------------------------
command -v cmake >/dev/null 2>&1 || die "cmake not found (need >= 3.18)"

if command -v g++ >/dev/null 2>&1; then
  gcc_major=$(g++ -dumpversion 2>/dev/null | cut -d. -f1)
  if [ -n "$gcc_major" ] && [ "$gcc_major" -ge 11 ]; then
    log "using g++ $gcc_major"
  else
    log "g++ found but version is too old ($gcc_major); needs >= 11 — will let CMake try anyway"
  fi
fi

# --- Clone -----------------------------------------------------------------
clone_or_keep "$ENGINE_DIR" "$REPO"

[ -f "$WRAPPER" ] || die "wrapper missing at $WRAPPER"
chmod +x "$WRAPPER" 2>/dev/null || true

# --- Compat shim -----------------------------------------------------------
mkdir -p "$ENGINE_DIR/shim"
cat > "$ENGINE_DIR/shim/perft_compat.h" << 'EOF'
// Linux build shim for perft_cpu_2026 (does NOT ship — generated by
// scripts/install-perft_cpu_2026.sh). Maps MSVC-only intrinsics that
// the upstream source uses unconditionally onto gcc/clang equivalents.
#pragma once
#ifndef _MSC_VER
#  if defined(__clang__)
#    define __assume(x) __builtin_assume(x)
#  else  // gcc and friends
#    define __assume(x) do { if (!(x)) __builtin_unreachable(); } while (0)
#  endif
#endif
EOF

# --- Build -----------------------------------------------------------------
HOST=$(detect_host)
SHIM_FLAGS="-include $(cd "$ENGINE_DIR" && pwd)/shim/perft_compat.h -fpermissive"
log "configuring (host=$HOST, cmake Release, with __assume shim + -fpermissive)"
(
  cd "$ENGINE_DIR"
  rm -rf build
  cmake -B build -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_CXX_FLAGS="$SHIM_FLAGS"
  cmake --build build --config Release -j
)

# Probe for the produced binary — CMake's output name depends on the project's
# CMakeLists. Default expected: build/perft_cpu (or perft_cpu_2026, etc.).
if [ ! -x "$BINARY" ]; then
  alt=$(find "$ENGINE_DIR/build" -maxdepth 2 -type f -perm -111 -name 'perft_cpu*' 2>/dev/null | head -1 || true)
  if [ -n "$alt" ] && [ "$alt" != "$BINARY" ]; then
    log "found binary at $alt — symlinking to $BINARY"
    ln -sf "$(basename "$alt")" "$BINARY" || ln -sf "$alt" "$BINARY"
  fi
fi
[ -x "$BINARY" ] || die "expected binary at $BINARY but it's missing"

# Verify via the WRAPPER.
out=$(verify_perft "$WRAPPER") || die "perft test failed (via wrapper)"

commit=$(git -C "$ENGINE_DIR" rev-parse --short HEAD 2>/dev/null || echo "")
[ -n "$commit" ] && log "perft_cpu_2026 commit: $commit → consider updating engines/$ENGINE.json's \"version\""

log "done. launch: $WRAPPER (binary: $BINARY)"
