#!/usr/bin/env bash
# Clone, build, and verify ZeroLogic → bin/zerologic/build/ZeroLogic.
#
# ZeroLogic (0xwurm) is a single-threaded UCI engine with built-in perft
# (`go perft <depth>`). It builds with CMake; CMakeLists requires C++23
# and pins `-mbmi2 -mbmi` plus `-Ofast -DNDEBUG -static` linking — so:
#   - Needs gcc >= 13 (or clang >= 16) for C++23 support.
#   - x86_64 only. ARM hosts cannot build it (BMI/BMI2 are x86 instructions).
#   - Static linking needs glibc-static / libstdc++-static available
#     (Ubuntu: `apt install libc6-dev libstdc++-static`).

ENGINE="zerologic"
REPO="https://github.com/0xwurm/ZeroLogic"
ENGINE_DIR="bin/zerologic"
BINARY="$ENGINE_DIR/build/ZeroLogic"

# shellcheck source=_common.sh
source "$(cd "$(dirname "$0")" && pwd)/_common.sh"

# --- Preflight -------------------------------------------------------------
HOST=$(detect_host)
case "$HOST" in
  *-x86_64) ;;
  *) die "ZeroLogic uses BMI/BMI2 (x86-only). Detected host: $HOST — cannot build here." ;;
esac

command -v cmake >/dev/null 2>&1 || die "cmake not found (need >= 3.26)"

if command -v g++ >/dev/null 2>&1; then
  gcc_major=$(g++ -dumpversion 2>/dev/null | cut -d. -f1)
  if [ -n "$gcc_major" ] && [ "$gcc_major" -lt 13 ]; then
    log "WARNING: g++ $gcc_major is below the recommended 13 for C++23 — build may fail"
  fi
fi

# --- Clone + build ---------------------------------------------------------
clone_or_keep "$ENGINE_DIR" "$REPO"

# ZeroLogic's CMakeLists hardcodes -DUSE_INTRIN, which makes stuff.h
# include <intrin.h>. That's an MSVC-only header — neither gcc nor clang
# on Linux ship a usable one. The only MSVC-ism actually consumed is
# __popcnt64. Drop a one-line shim into a private include dir mapping it
# to __builtin_popcountll, then point the compiler at that dir via
# CPLUS_INCLUDE_PATH (which gcc and clang honour additively, and which
# CMake doesn't override even when CMakeLists assigns CMAKE_CXX_FLAGS).
mkdir -p "$ENGINE_DIR/shim"
cat > "$ENGINE_DIR/shim/intrin.h" << 'EOF'
// Linux build shim for ZeroLogic (does NOT ship — generated by
// scripts/install-zerologic.sh). ZeroLogic only uses __popcnt64 from
// <intrin.h>; everything else (PEXT, TZCNT, BLSI, BLSR) comes from
// <immintrin.h>, which gcc/clang have natively.
#pragma once
#define __popcnt64(x) __builtin_popcountll((unsigned long long)(x))
EOF

log "configuring (cmake Release, with intrin.h shim)"
(
  cd "$ENGINE_DIR"
  rm -rf build
  CPLUS_INCLUDE_PATH="$PWD/shim${CPLUS_INCLUDE_PATH:+:$CPLUS_INCLUDE_PATH}" \
    cmake -B build -DCMAKE_BUILD_TYPE=Release
  CPLUS_INCLUDE_PATH="$PWD/shim${CPLUS_INCLUDE_PATH:+:$CPLUS_INCLUDE_PATH}" \
    cmake --build build --config Release -j
)

[ -x "$BINARY" ] || die "expected binary at $BINARY but it's missing"

out=$(verify_perft "$BINARY") || die "perft test failed"

# ZeroLogic doesn't tag a UCI banner version we can pin against, so fall
# back to the cloned git commit hash.
commit=$(git -C "$ENGINE_DIR" rev-parse --short HEAD 2>/dev/null || echo "")
[ -n "$commit" ] && log "zerologic commit: $commit → consider updating engines/$ENGINE.json's \"version\""

log "done. launch: $BINARY"
