#!/usr/bin/env bash
# Clone, build, and verify perft_cpu_2026 → bin/perft_cpu_2026/build/perft_cpu.
#
# perft_cpu_2026 (Ankan Banerjee) is a perft-only CLI tool, not a UCI engine.
# PerftWar drives it via wrappers/perft_cpu_2026/run.sh.
#
# Build notes (all the workarounds, learned the hard way):
#   - Requires clang++-20 (or any clang with `-fms-extensions`). gcc 13 trips
#     on two-phase template lookup for `countMoves` even with `-fpermissive`.
#   - Force-includes shim/perft_compat.h, which:
#       * Defines __assume(x) → __builtin_assume / __builtin_unreachable.
#       * #define findSliderAttacksOnly4 findSliderAttacksOnly4_UNUSED
#         (upstream rename mismatch — caller never updated).
#   - Needs `-fms-extensions` for __declspec attributes.
#   - Needs `-march=native` (or equivalent) — AVX intrinsics in
#     cliff_probe.cpp / leaf_batch_avx2.cpp aren't auto-enabled by CMakeLists.

ENGINE="perft_cpu_2026"
REPO="https://github.com/ankan-ban/perft_cpu_2026"
ENGINE_DIR="bin/perft_cpu_2026"
BINARY="$ENGINE_DIR/build/perft_cpu"
WRAPPER="wrappers/perft_cpu_2026/run.sh"

# shellcheck source=_common.sh
source "$(cd "$(dirname "$0")" && pwd)/_common.sh"

# --- Toolchain preflight ---------------------------------------------------
command -v cmake >/dev/null 2>&1 || die "cmake not found (need >= 3.18)"

# Pick a clang++ >= 16. Match install-stockdory.sh's discovery pattern.
_clang_major() {
  command -v "$1" >/dev/null 2>&1 || { echo ""; return; }
  "$1" --version 2>/dev/null | head -1 | sed -nE 's/.*version ([0-9]+).*/\1/p'
}
CLANGXX=""
v=$(_clang_major clang++)
if [ -n "$v" ] && [ "$v" -ge 16 ]; then
  CLANGXX=clang++
fi
if [ -z "$CLANGXX" ]; then
  for cand in clang++-25 clang++-24 clang++-23 clang++-22 clang++-21 clang++-20 clang++-19 clang++-18 clang++-17 clang++-16; do
    if command -v "$cand" >/dev/null 2>&1; then
      CLANGXX="$cand"
      break
    fi
  done
fi
[ -n "$CLANGXX" ] || die "clang++ >= 16 not found (apt: install via apt.llvm.org/llvm.sh)"
CLANGC="${CLANGXX/clang++/clang}"
log "using compiler: $CLANGXX (and $CLANGC)"

# --- Clone -----------------------------------------------------------------
clone_or_keep "$ENGINE_DIR" "$REPO"

[ -f "$WRAPPER" ] || die "wrapper missing at $WRAPPER"
chmod +x "$WRAPPER" 2>/dev/null || true

# --- Compat shim -----------------------------------------------------------
mkdir -p "$ENGINE_DIR/shim"
cat > "$ENGINE_DIR/shim/perft_compat.h" << 'EOF'
// Linux build shim for perft_cpu_2026 (does NOT ship — generated by
// scripts/install-perft_cpu_2026.sh). Maps MSVC-only intrinsics and
// stale upstream rename mismatches onto Linux toolchains.
#pragma once
#ifndef _MSC_VER
#  if defined(__clang__)
#    define __assume(x) __builtin_assume(x)
#  else
#    define __assume(x) do { if (!(x)) __builtin_unreachable(); } while (0)
#  endif
#endif

// `findSliderAttacksOnly4_UNUSED` is the declared name (line 817) but
// callers at lines 2338/2671 reference the unprefixed name. Bridge.
#define findSliderAttacksOnly4 findSliderAttacksOnly4_UNUSED
EOF

# --- Build -----------------------------------------------------------------
HOST=$(detect_host)
SHIM_PATH="$(cd "$ENGINE_DIR" && pwd)/shim/perft_compat.h"
CXX_FLAGS="-include $SHIM_PATH -fms-extensions -march=native"
log "configuring (host=$HOST, cmake Release, $CLANGXX + shim + -fms-extensions + -march=native)"
(
  cd "$ENGINE_DIR"
  rm -rf build
  cmake -B build -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_CXX_COMPILER="$CLANGXX" \
        -DCMAKE_C_COMPILER="$CLANGC" \
        -DCMAKE_CXX_FLAGS="$CXX_FLAGS"
  cmake --build build --config Release -j
)

# Probe for the produced binary — CMake's output name depends on the project's
# CMakeLists. Default expected: build/perft_cpu.
if [ ! -x "$BINARY" ]; then
  alt=$(find "$ENGINE_DIR/build" -maxdepth 2 -type f -perm -111 -name 'perft_cpu*' 2>/dev/null | head -1 || true)
  if [ -n "$alt" ] && [ "$alt" != "$BINARY" ]; then
    log "found binary at $alt — symlinking to $BINARY"
    ln -sf "$(basename "$alt")" "$BINARY" || ln -sf "$alt" "$BINARY"
  fi
fi
[ -x "$BINARY" ] || die "expected binary at $BINARY but it's missing"

# Verify via the WRAPPER.
out=$(verify_perft "$WRAPPER") || die "perft test failed (via wrapper)"

commit=$(git -C "$ENGINE_DIR" rev-parse --short HEAD 2>/dev/null || echo "")
[ -n "$commit" ] && log "perft_cpu_2026 commit: $commit → consider updating engines/$ENGINE.json's \"version\""

log "done. launch: $WRAPPER (binary: $BINARY)"
